/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsNexusRouteImport } from './routes/what-is-nexus'
import { Route as IndexRouteImport } from './routes/index'

const WhatIsNexusRoute = WhatIsNexusRouteImport.update({
  id: '/what-is-nexus',
  path: '/what-is-nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/what-is-nexus': typeof WhatIsNexusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/what-is-nexus': typeof WhatIsNexusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/what-is-nexus': typeof WhatIsNexusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/what-is-nexus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/what-is-nexus'
  id: '__root__' | '/' | '/what-is-nexus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhatIsNexusRoute: typeof WhatIsNexusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-nexus': {
      id: '/what-is-nexus'
      path: '/what-is-nexus'
      fullPath: '/what-is-nexus'
      preLoaderRoute: typeof WhatIsNexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhatIsNexusRoute: WhatIsNexusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
